name: personal_finance
# TODO: Локализовать описание через .arb файлы (рекомендуется).
# Например, в intl_en.arb: "appDescription": "A new Flutter project."
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  fl_chart: ^0.70.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true # Добавляем для поддержки генерации локализаций