name: aia_wallet
description: "A new Flutter project."

publish_to: 'none'

version: 0.0.1+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  fl_chart: ^0.70.2
  provider: ^6.1.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  assets:
    - assets/images/app_logo.png
    - assets/images/aia_logo_b.png
    - assets/images/aia_logo_w.png
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21