class CurrencyApiService {
  // Static currency data (as provided)
  static const Map<String, dynamic> _currencyData = {
    "success":true,
    "timestamp":1743859144,
    "base":"EUR",
    "date":"2025-04-05",
    "rates":{
      "AED":4.02547,
      "AFN":78.958383,
      "ALL":99.102869,
      "AMD":431.181955,
      "ANG":1.961978,
      "AOA":1003.890567,
      "ARS":1184.765046,
      "AUD":1.813586,
      "AWG":1.97271,
      "AZN":1.867466,
      "BAM":1.955265,
      "BBD":2.22659,
      "BDT":133.983319,
      "BGN":1.955265,
      "BHD":0.412787,
      "BIF":3277.602688,
      "BMD":1.09595,
      "BND":1.474296,
      "BOB":7.619914,
      "BRL":6.405394,
      "BSD":1.102698,
      "BTC":1.3020076e-5,
      "BTN":94.079244,
      "BWP":15.358795,
      "BYN":3.608812,
      "BYR":21480.619234,
      "BZD":2.215094,
      "CAD":1.559263,
      "CDF":3148.664634,
      "CHF":0.944431,
      "CLF":0.02729,
      "CLP":1047.223301,
      "CNY":7.980215,
      "CNH":7.994999,
      "COP":4582.945323,
      "CRC":557.847278,
      "CUC":1.09595,
      "CUP":29.042674,
      "CVE":110.234821,
      "CZK":25.256829,
      "DJF":196.376238,
      "DKK":7.461451,
      "DOP":69.640934,
      "DZD":146.03502,
      "EGP":55.406831,
      "ERN":16.439249,
      "ETB":145.347308,
      "EUR":1,
      "FJD":2.537019,
      "FKP":0.847795,
      "GBP":0.850992,
      "GEL":3.01429,
      "GGP":0.847795,
      "GHS":17.092321,
      "GIP":0.847795,
      "GMD":78.364643,
      "GNF":9543.387299,
      "GTQ":8.51067,
      "GYD":230.706839,
      "HKD":8.520358,
      "HNL":28.214276,
      "HRK":7.531044,
      "HTG":144.290497,
      "HUF":405.95125,
      "IDR":18351.682095,
      "ILS":4.102536,
      "IMP":0.847795,
      "INR":93.736057,
      "IQD":1444.604509,
      "IRR":46139.49374,
      "ISK":144.852129,
      "JEP":0.847795,
      "JMD":173.912388,
      "JOD":0.776923,
      "JPY":161.154005,
      "KES":142.530979,
      "KGS":95.094267,
      "KHR":4414.791359,
      "KMF":493.729615,
      "KPW":986.361205,
      "KRW":1599.550347,
      "KWD":0.337323,
      "KYD":0.918948,
      "KZT":559.11693,
      "LAK":23885.460858,
      "LBP":98806.249733,
      "LKR":326.960488,
      "LRD":220.54962,
      "LSL":21.028443,
      "LTL":3.236056,
      "LVL":0.66293,
      "LYD":5.33354,
      "MAD":10.502325,
      "MDL":19.485665,
      "MGA":5113.600046,
      "MKD":61.518158,
      "MMK":2300.919896,
      "MNT":3846.361639,
      "MOP":8.828083,
      "MRU":43.97796,
      "MUR":48.956499,
      "MVR":16.881727,
      "MWK":1912.176502,
      "MXN":22.397605,
      "MYR":4.862772,
      "MZN":70.042575,
      "NAD":21.028443,
      "NGN":1679.894432,
      "NIO":40.578891,
      "NOK":11.801632,
      "NPR":150.52679,
      "NZD":1.958628,
      "OMR":0.421635,
      "PAB":1.102798,
      "PEN":4.052091,
      "PGK":4.551754,
      "PHP":62.891131,
      "PKR":309.568949,
      "PLN":4.295424,
      "PYG":8840.579707,
      "QAR":4.019799,
      "RON":4.977847,
      "RSD":117.117937,
      "RUB":92.974546,
      "RWF":1589.164933,
      "SAR":4.110175,
      "SBD":9.114284,
      "SCR":15.716697,
      "SDG":658.12198,
      "SEK":10.951065,
      "SGD":1.474715,
      "SHP":0.861245,
      "SLE":24.933268,
      "SLL":22981.523891,
      "SOS":630.227462,
      "SRD":40.162734,
      "STD":22683.951476,
      "SVC":9.649358,
      "SYP":14249.994157,
      "SZL":21.036241,
      "THB":37.713872,
      "TJS":12.003414,
      "TMT":3.835825,
      "TND":3.376876,
      "TOP":2.566829,
      "TRY":41.607525,
      "TTD":7.469955,
      "TWD":36.360884,
      "TZS":2949.992378,
      "UAH":45.388374,
      "UGX":4030.896458,
      "USD":1.09595,
      "UYU":46.647229,
      "UZS":14248.099286,
      "VES":76.89351,
      "VND":28280.988741,
      "VUV":134.896075,
      "WST":3.078778,
      "XAF":655.777467,
      "XAG":0.037037,
      "XAU":0.000361,
      "XCD":2.96186,
      "XDR":0.815577,
      "XOF":655.777467,
      "XPF":119.331742,
      "YER":269.220506,
      "ZAR":20.960317,
      "ZMK":9864.868719,
      "ZMW":30.57363,
      "ZWL":352.89544
    }
  };

  // Mapping of currency codes to country names
  static const Map<String, String> _currencyToCountry = {
    "AED": "United Arab Emirates",
    "AFN": "Afghanistan",
    "ALL": "Albania",
    "AMD": "Armenia",
    "ANG": "Netherlands Antilles",
    "AOA": "Angola",
    "ARS": "Argentina",
    "AUD": "Australia",
    "AWG": "Aruba",
    "AZN": "Azerbaijan",
    "BAM": "Bosnia and Herzegovina",
    "BBD": "Barbados",
    "BDT": "Bangladesh",
    "BGN": "Bulgaria",
    "BHD": "Bahrain",
    "BIF": "Burundi",
    "BMD": "Bermuda",
    "BND": "Brunei",
    "BOB": "Bolivia",
    "BRL": "Brazil",
    "BSD": "Bahamas",
    "BTC": "Bitcoin",
    "BTN": "Bhutan",
    "BWP": "Botswana",
    "BYN": "Belarus",
    "BYR": "Belarus (Old)",
    "BZD": "Belize",
    "CAD": "Canada",
    "CDF": "Democratic Republic of the Congo",
    "CHF": "Switzerland",
    "CLF": "Chile (Unit of Account)",
    "CLP": "Chile",
    "CNY": "China",
    "CNH": "China (Offshore)",
    "COP": "Colombia",
    "CRC": "Costa Rica",
    "CUC": "Cuba (Convertible Peso)",
    "CUP": "Cuba",
    "CVE": "Cape Verde",
    "CZK": "Czech Republic",
    "DJF": "Djibouti",
    "DKK": "Denmark",
    "DOP": "Dominican Republic",
    "DZD": "Algeria",
    "EGP": "Egypt",
    "ERN": "Eritrea",
    "ETB": "Ethiopia",
    "EUR": "Europe",
    "FJD": "Fiji",
    "FKP": "Falkland Islands",
    "GBP": "United Kingdom",
    "GEL": "Georgia",
    "GGP": "Guernsey",
    "GHS": "Ghana",
    "GIP": "Gibraltar",
    "GMD": "Gambia",
    "GNF": "Guinea",
    "GTQ": "Guatemala",
    "GYD": "Guyana",
    "HKD": "Hong Kong",
    "HNL": "Honduras",
    "HRK": "Croatia",
    "HTG": "Haiti",
    "HUF": "Hungary",
    "IDR": "Indonesia",
    "ILS": "Israel",
    "IMP": "Isle of Man",
    "INR": "India",
    "IQD": "Iraq",
    "IRR": "Iran",
    "ISK": "Iceland",
    "JEP": "Jersey",
    "JMD": "Jamaica",
    "JOD": "Jordan",
    "JPY": "Japan",
    "KES": "Kenya",
    "KGS": "Kyrgyzstan",
    "KHR": "Cambodia",
    "KMF": "Comoros",
    "KPW": "North Korea",
    "KRW": "South Korea",
    "KWD": "Kuwait",
    "KYD": "Cayman Islands",
    "KZT": "Kazakhstan",
    "LAK": "Laos",
    "LBP": "Lebanon",
    "LKR": "Sri Lanka",
    "LRD": "Liberia",
    "LSL": "Lesotho",
    "LTL": "Lithuania (Old)",
    "LVL": "Latvia (Old)",
    "LYD": "Libya",
    "MAD": "Morocco",
    "MDL": "Moldova",
    "MGA": "Madagascar",
    "MKD": "North Macedonia",
    "MMK": "Myanmar",
    "MNT": "Mongolia",
    "MOP": "Macau",
    "MRU": "Mauritania",
    "MUR": "Mauritius",
    "MVR": "Maldives",
    "MWK": "Malawi",
    "MXN": "Mexico",
    "MYR": "Malaysia",
    "MZN": "Mozambique",
    "NAD": "Namibia",
    "NGN": "Nigeria",
    "NIO": "Nicaragua",
    "NOK": "Norway",
    "NPR": "Nepal",
    "NZD": "New Zealand",
    "OMR": "Oman",
    "PAB": "Panama",
    "PEN": "Peru",
    "PGK": "Papua New Guinea",
    "PHP": "Philippines",
    "PKR": "Pakistan",
    "PLN": "Poland",
    "PYG": "Paraguay",
    "QAR": "Qatar",
    "RON": "Romania",
    "RSD": "Serbia",
    "RUB": "Russia",
    "RWF": "Rwanda",
    "SAR": "Saudi Arabia",
    "SBD": "Solomon Islands",
    "SCR": "Seychelles",
    "SDG": "Sudan",
    "SEK": "Sweden",
    "SGD": "Singapore",
    "SHP": "Saint Helena",
    "SLE": "Sierra Leone",
    "SLL": "Sierra Leone (Old)",
    "SOS": "Somalia",
    "SRD": "Suriname",
    "STD": "São Tomé and Príncipe (Old)",
    "SVC": "El Salvador",
    "SYP": "Syria",
    "SZL": "Eswatini",
    "THB": "Thailand",
    "TJS": "Tajikistan",
    "TMT": "Turkmenistan",
    "TND": "Tunisia",
    "TOP": "Tonga",
    "TRY": "Turkey",
    "TTD": "Trinidad and Tobago",
    "TWD": "Taiwan",
    "TZS": "Tanzania",
    "UAH": "Ukraine",
    "UGX": "Uganda",
    "USD": "United States",
    "UYU": "Uruguay",
    "UZS": "Uzbekistan",
    "VES": "Venezuela",
    "VND": "Vietnam",
    "VUV": "Vanuatu",
    "WST": "Samoa",
    "XAF": "Central African CFA Franc",
    "XAG": "Silver (Troy Ounce)",
    "XAU": "Gold (Troy Ounce)",
    "XCD": "Eastern Caribbean Dollar",
    "XDR": "Special Drawing Rights",
    "XOF": "West African CFA Franc",
    "XPF": "CFP Franc",
    "YER": "Yemen",
    "ZAR": "South Africa",
    "ZMK": "Zambia (Old)",
    "ZMW": "Zambia",
    "ZWL": "Zimbabwe"
  };

  // Mapping of currency codes to their symbols
  static const Map<String, String> _currencySymbols = {
    "AED": "د.إ",
    "AFN": "؋",
    "ALL": "L",
    "AMD": "֏",
    "ANG": "ƒ",
    "AOA": "Kz",
    "ARS": "\$",
    "AUD": "\$",
    "AWG": "ƒ",
    "AZN": "₼",
    "BAM": "KM",
    "BBD": "\$",
    "BDT": "৳",
    "BGN": "лв",
    "BHD": ".د.ب",
    "BIF": "FBu",
    "BMD": "\$",
    "BND": "\$",
    "BOB": "Bs.",
    "BRL": "R\$",
    "BSD": "\$",
    "BTC": "₿",
    "BTN": "Nu.",
    "BWP": "P",
    "BYN": "Br",
    "BYR": "Br",
    "BZD": "BZ\$",
    "CAD": "\$",
    "CDF": "FC",
    "CHF": "Fr.",
    "CLF": "UF",
    "CLP": "\$",
    "CNY": "¥",
    "CNH": "¥",
    "COP": "\$",
    "CRC": "₡",
    "CUC": "\$",
    "CUP": "₱",
    "CVE": "\$",
    "CZK": "Kč",
    "DJF": "Fdj",
    "DKK": "kr",
    "DOP": "RD\$",
    "DZD": "دج",
    "EGP": "£",
    "ERN": "Nfk",
    "ETB": "Br",
    "EUR": "€",
    "FJD": "\$",
    "FKP": "£",
    "GBP": "£",
    "GEL": "₾",
    "GGP": "£",
    "GHS": "₵",
    "GIP": "£",
    "GMD": "D",
    "GNF": "FG",
    "GTQ": "Q",
    "GYD": "\$",
    "HKD": "\$",
    "HNL": "L",
    "HRK": "kn",
    "HTG": "G",
    "HUF": "Ft",
    "IDR": "Rp",
    "ILS": "₪",
    "IMP": "£",
    "INR": "₹",
    "IQD": "ع.د",
    "IRR": "﷼",
    "ISK": "kr",
    "JEP": "£",
    "JMD": "J\$",
    "JOD": "د.ا",
    "JPY": "¥",
    "KES": "KSh",
    "KGS": "Сом",
    "KHR": "៛",
    "KMF": "CF",
    "KPW": "₩",
    "KRW": "₩",
    "KWD": "د.ك",
    "KYD": "\$",
    "KZT": "₸",
    "LAK": "₭",
    "LBP": "ل.ل",
    "LKR": "₨",
    "LRD": "\$",
    "LSL": "L",
    "LTL": "Lt",
    "LVL": "Ls",
    "LYD": "ل.د",
    "MAD": "د.م.",
    "MDL": "L",
    "MGA": "Ar",
    "MKD": "ден",
    "MMK": "K",
    "MNT": "₮",
    "MOP": "MOP\$",
    "MRU": "UM",
    "MUR": "₨",
    "MVR": "Rf",
    "MWK": "MK",
    "MXN": "\$",
    "MYR": "RM",
    "MZN": "MT",
    "NAD": "\$",
    "NGN": "₦",
    "NIO": "C\$",
    "NOK": "kr",
    "NPR": "₨",
    "NZD": "\$",
    "OMR": "ر.ع.",
    "PAB": "B/.",
    "PEN": "S/.",
    "PGK": "K",
    "PHP": "₱",
    "PKR": "₨",
    "PLN": "zł",
    "PYG": "₲",
    "QAR": "ر.ق",
    "RON": "lei",
    "RSD": "дин",
    "RUB": "₽",
    "RWF": "FRw",
    "SAR": "ر.س",
    "SBD": "\$",
    "SCR": "₨",
    "SDG": "ج.س.",
    "SEK": "kr",
    "SGD": "\$",
    "SHP": "£",
    "SLE": "Le",
    "SLL": "Le",
    "SOS": "Sh",
    "SRD": "\$",
    "STD": "Db",
    "SVC": "\$",
    "SYP": "£",
    "SZL": "E",
    "THB": "฿",
    "TJS": "SM",
    "TMT": "m",
    "TND": "د.ت",
    "TOP": "T\$",
    "TRY": "₺",
    "TTD": "TT\$",
    "TWD": "NT\$",
    "TZS": "TSh",
    "UAH": "₴",
    "UGX": "USh",
    "USD": "\$",
    "UYU": "\$U",
    "UZS": "сўм",
    "VES": "Bs.",
    "VND": "₫",
    "VUV": "VT",
    "WST": "WS\$",
    "XAF": "FCFA",
    "XAG": "XAG",
    "XAU": "XAU",
    "XCD": "\$",
    "XDR": "XDR",
    "XOF": "CFA",
    "XPF": "₣",
    "YER": "﷼",
    "ZAR": "R",
    "ZMK": "ZK",
    "ZMW": "ZK",
    "ZWL": "\$"
  };

  // Mapping of currency codes to flag emojis
  static const Map<String, String> _currencyFlags = {
    "AED": "🇦🇪",
    "AFN": "🇦🇫",
    "ALL": "🇦🇱",
    "AMD": "🇦🇲",
    "ANG": "🇦🇳",
    "AOA": "🇦🇴",
    "ARS": "🇦🇷",
    "AUD": "🇦🇺",
    "AWG": "🇦🇼",
    "AZN": "🇦🇿",
    "BAM": "🇧🇦",
    "BBD": "🇧🇧",
    "BDT": "🇧🇩",
    "BGN": "🇧🇬",
    "BHD": "🇧🇭",
    "BIF": "🇧🇮",
    "BMD": "🇧🇲",
    "BND": "🇧🇳",
    "BOB": "🇧🇴",
    "BRL": "🇧🇷",
    "BSD": "🇧🇸",
    "BTC": "", // No flag for Bitcoin
    "BTN": "🇧🇹",
    "BWP": "🇧🇼",
    "BYN": "🇧🇾",
    "BYR": "🇧🇾",
    "BZD": "🇧🇿",
    "CAD": "🇨🇦",
    "CDF": "🇨🇩",
    "CHF": "🇨🇭",
    "CLF": "🇨🇱",
    "CLP": "🇨🇱",
    "CNY": "🇨🇳",
    "CNH": "🇨🇳",
    "COP": "🇨🇴",
    "CRC": "🇨🇷",
    "CUC": "🇨🇺",
    "CUP": "🇨🇺",
    "CVE": "🇨🇻",
    "CZK": "🇨🇿",
    "DJF": "🇩🇯",
    "DKK": "🇩🇰",
    "DOP": "🇩🇴",
    "DZD": "🇩🇿",
    "EGP": "🇪🇬",
    "ERN": "🇪🇷",
    "ETB": "🇪🇹",
    "EUR": "🇪🇺", // EU flag for Euro
    "FJD": "🇫🇯",
    "FKP": "🇫🇰",
    "GBP": "🇬🇧",
    "GEL": "🇬🇪",
    "GGP": "🇬🇬",
    "GHS": "🇬🇭",
    "GIP": "🇬🇮",
    "GMD": "🇬🇲",
    "GNF": "🇬🇳",
    "GTQ": "🇬🇹",
    "GYD": "🇬🇾",
    "HKD": "🇭🇰",
    "HNL": "🇭🇳",
    "HRK": "🇭🇷",
    "HTG": "🇭🇹",
    "HUF": "🇭🇺",
    "IDR": "🇮🇩",
    "ILS": "🇮🇱",
    "IMP": "🇮🇲",
    "INR": "🇮🇳",
    "IQD": "🇮🇶",
    "IRR": "🇮🇷",
    "ISK": "🇮🇸",
    "JEP": "🇯🇪",
    "JMD": "🇯🇲",
    "JOD": "🇯🇴",
    "JPY": "🇯🇵",
    "KES": "🇰🇪",
    "KGS": "🇰🇬",
    "KHR": "🇰🇭",
    "KMF": "🇰🇲",
    "KPW": "🇰🇵",
    "KRW": "🇰🇷",
    "KWD": "🇰🇼",
    "KYD": "🇰🇾",
    "KZT": "🇰🇿",
    "LAK": "🇱🇦",
    "LBP": "🇱🇧",
    "LKR": "🇱🇰",
    "LRD": "🇱🇷",
    "LSL": "🇱🇸",
    "LTL": "🇱🇹",
    "LVL": "🇱🇻",
    "LYD": "🇱🇾",
    "MAD": "🇲🇦",
    "MDL": "🇲🇩",
    "MGA": "🇲🇬",
    "MKD": "🇲🇰",
    "MMK": "🇲🇲",
    "MNT": "🇲🇳",
    "MOP": "🇲🇴",
    "MRU": "🇲🇷",
    "MUR": "🇲🇺",
    "MVR": "🇲🇻",
    "MWK": "🇲🇼",
    "MXN": "🇲🇽",
    "MYR": "🇲🇾",
    "MZN": "🇲🇿",
    "NAD": "🇳🇦",
    "NGN": "🇳🇬",
    "NIO": "🇳🇮",
    "NOK": "🇳🇴",
    "NPR": "🇳🇵",
    "NZD": "🇳🇿",
    "OMR": "🇴🇲",
    "PAB": "🇵🇦",
    "PEN": "🇵🇪",
    "PGK": "🇵🇬",
    "PHP": "🇵🇭",
    "PKR": "🇵🇰",
    "PLN": "🇵🇱",
    "PYG": "🇵🇾",
    "QAR": "🇶🇦",
    "RON": "🇷🇴",
    "RSD": "🇷🇸",
    "RUB": "🇷🇺",
    "RWF": "🇷🇼",
    "SAR": "🇸🇦",
    "SBD": "🇸🇧",
    "SCR": "🇸🇨",
    "SDG": "🇸🇩",
    "SEK": "🇸🇪",
    "SGD": "🇸🇬",
    "SHP": "🇸🇭",
    "SLE": "🇸🇱",
    "SLL": "🇸🇱",
    "SOS": "🇸🇴",
    "SRD": "🇸🇷",
    "STD": "🇸🇹",
    "SVC": "🇸🇻",
    "SYP": "🇸🇾",
    "SZL": "🇸🇿",
    "THB": "🇹🇭",
    "TJS": "🇹🇯",
    "TMT": "🇹🇲",
    "TND": "🇹🇳",
    "TOP": "🇹🇴",
    "TRY": "🇹🇷",
    "TTD": "🇹🇹",
    "TWD": "🇹🇼",
    "TZS": "🇹🇿",
    "UAH": "🇺🇦",
    "UGX": "🇺🇬",
    "USD": "🇺🇸",
    "UYU": "🇺🇾",
    "UZS": "🇺🇿",
    "VES": "🇻🇪",
    "VND": "🇻🇳",
    "VUV": "🇻🇺",
    "WST": "🇼🇸",
    "XAF": "🇨🇲", // Cameroon as representative
    "XAG": "", // No flag for Silver
    "XAU": "", // No flag for Gold
    "XCD": "🇦🇬", // Antigua and Barbuda as representative
    "XDR": "", // No flag for SDR
    "XOF": "🇸🇳", // Senegal as representative
    "XPF": "🇵🇫", // French Polynesia as representative
    "YER": "🇾🇪",
    "ZAR": "🇿🇦",
    "ZMK": "🇿🇲",
    "ZMW": "🇿🇲",
    "ZWL": "🇿🇼"
  };

  /// Returns the static exchange rates with EUR as the base.
  Map<String, double> getExchangeRates() {
    final rates = _currencyData['rates'] as Map<String, dynamic>;
    return rates.map((key, value) => MapEntry(key, (value as num).toDouble()));
  }

  /// Gets the conversion rate from `fromCurrency` to `toCurrency`.
  /// Since the data uses EUR as base, we calculate the rate via EUR.
  double getConversionRate(String fromCurrency, String toCurrency) {
    final rates = getExchangeRates();

    if (!rates.containsKey(fromCurrency) || !rates.containsKey(toCurrency)) {
      throw Exception('Currency not supported: $fromCurrency or $toCurrency');
    }

    final fromRate = rates[fromCurrency]!; // Rate of fromCurrency to EUR
    final toRate = rates[toCurrency]!;     // Rate of toCurrency to EUR

    // Calculate rate from fromCurrency to toCurrency
    // Example: KGS to USD = (EUR/USD) / (EUR/KGS)
    return toRate / fromRate;
  }

  /// Returns a list of all available currency codes.
  List<String> getAllCurrencies() {
    final rates = _currencyData['rates'] as Map<String, dynamic>;
    return rates.keys.toList();
  }

  /// Returns the country name for a given currency code.
  String getCountryForCurrency(String currency) {
    return _currencyToCountry[currency] ?? 'Unknown';
  }

  /// Returns a map of currency codes to country names.
  Map<String, String> getCurrencyToCountryMap() {
    return Map.from(_currencyToCountry);
  }

  /// Returns the symbol for a given currency code.
  /// If no symbol is defined, returns the currency code itself.
  String getCurrencySymbol(String currency) {
    return _currencySymbols[currency] ?? currency;
  }

  /// Returns a map of currency codes to their symbols.
  Map<String, String> getCurrencySymbolsMap() {
    return Map.from(_currencySymbols);
  }

  /// Returns the flag emoji for a given currency code.
  /// If no flag is defined, returns an empty string.
  String getCurrencyFlag(String currency) {
    return _currencyFlags[currency] ?? '';
  }

  /// Returns a map of currency codes to their flag emojis.
  Map<String, String> getCurrencyFlagsMap() {
    return Map.from(_currencyFlags);
  }
}